export default {
    // Scales
    SCALE_LINEAR: 'SCALE_LINEAR',
    SCALE_LOG: 'SCALE_LOG',
    SCALE_BIEXP: 'SCALE_BIEXP',
    SCALE_ARCSIN: 'SCALE_ARCSIN',
    // Machine Types
    MACHINE_CYTOF: 'CYTOF',
    MACHINE_FLORESCENT: 'FLORESCENT',
    // Gate types
    GATE_TYPE_POLYGON: 'GATE_TYPE_POLYGON',
    GATE_TYPE_NEGATIVE: 'GATE_TYPE_NEGATIVE',
    GATE_TYPE_COMBO: 'GATE_TYPE_COMBO',
    // Gate creators
    GATE_CREATOR_MANUAL: 'GATE_CREATOR_MANUAL',
    GATE_CREATOR_PERSISTENT_HOMOLOGY: 'GATE_CREATOR_PERSISTENT_HOMOLOGY',
    // Gate error handlers
    GATE_ERROR_HANDLER_AUTO_ANCHORING: 'GATE_ERROR_HANDLER_AUTO_ANCHORING',
    // Status / exit codes for generic use
    STATUS_SUCCESS: 'STATUS_SUCCESS',
    STATUS_FAIL: 'STATUS_FAIL',
    // Keyboard character codes
    CHARACTER_CODE_ESCAPE: 27,
    CHARACTER_CODE_LEFT_ARROW: 37,
    CHARACTER_CODE_UP_ARROW: 38,
    CHARACTER_CODE_RIGHT_ARROW: 39,
    CHARACTER_CODE_DOWN_ARROW: 40
}